SantaFeBD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_view
from . import views

urlpatterns = [
    url(r'^persons/', include('persons.urls', namespace='persons')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
]

persons/urls.py
from django.conf.urls import url

from .views import (UserLoginView,
                    loginForm,
                    logoutView,
                    person_create,
                    person_update,
                    person_delete,
                    UserCreateView,
                    persons_list_creator,
                    users_list,
                    disable_user,
                    enable_user,
                    search,
                    results,
                    person_list,
                    successful,
                    successful_user,
                    successful_edition,
                    successful_deletion,
)

urlpatterns = [
    url('^login/$', UserLoginView.as_view(), name='login'),
    url('^logout/$', logoutView, name='logout'),
    url('^tologin/$', loginForm, name='tologin'),
    url('^create/$', person_create, name='create'),
    url('^edit/(?P<pk>\d+)/$', person_update, name='update'),
    url('^delete/(?P<pk>\d+)/$', person_delete, name='delete'),
    url('^createuser/$', UserCreateView.as_view(), name='createuser'),
    url('^users/$', users_list, name='users'),
    url('^personsuser/(?P<pk_user>\d+)/$', persons_list_creator, name='personsuser'),
    url('^disable/(?P<pk>\d+)/$', disable_user, name='disable'),
    url('^enable/(?P<pk>\d+)/$', enable_user, name='enable'),
    url('^search/$', search, name='search'),
    url('^results/$', results, name='results'),
    url('^successful/$', successful, name='successful'),
    url('^successfuluser/$', successful_user, name='succesfuluser'),
    url('^successfuledition/$', successful_edition, name='successfuledition'),
    url('^successfuldeletion/$', successful_deletion, name='successfuldeletion'),
    url('^$', person_list, name='all'),
]

persons/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=70)
    email = models.EmailField()
    phone = models.CharField(max_length=14)
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    userCreator = models.ForeignKey(settings.AUTH_USER_MODEL)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

persons/forms.py
from django.contrib.auth.models import User
from .models import Person
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class CreateUserForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirma Password')

    class Meta:
        model = User
        fields = ['username', 'password', 'password2']

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password != password2:
            raise forms.ValidationError("Los password deben ser iguales")


class PersonForm(forms.ModelForm):
    CHOICE = (('Femenino', 'Femenino'), ('Masculino', 'Masculino'))
    gender = forms.ChoiceField(widget=forms.Select, choices=CHOICE, label='Genero',)
    name = forms.CharField(label='Nombre', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone = forms.CharField(label='Teléfono',
                            widget=forms.NumberInput(attrs={'class': 'form-control'}))
    age = forms.IntegerField(label='Edad', widget=forms.NumberInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Person
        fields = ['name', 'email', 'phone', 'age', 'gender']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_qs = Person.objects.filter(email=email)
        if email_qs.exists():
            if self.instance.pk != email_qs[0].pk:
                raise forms.ValidationError("Este email ya ha sido registrado")
        return email

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if (age > 110) or (0 > age):
            raise forms.ValidationError("Edad inávlida")
        return age

persons/views.py
from django.shortcuts import render, get_object_or_404, Http404, redirect
from .forms import UserForm, PersonForm, CreateUserForm
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.contrib.auth.models import User
from .models import *
from django.views.generic.edit import CreateView
# Create your views here.

def loginForm(request):
    if request.user.is_authenticated():
        return redirect('/')
    return render(request, 'persons/login.html')

def logoutView(request):
    if not request.user.is_authenticated():
        raise Http404

    if not request.user.is_superuser:
        user = request.user
        user.is_active = False
        user.save()
        logout(request)
        return redirect('/')
    logout(request)
    return redirect('/')

def persons_list_creator(request, pk_user):
    if not request.user.is_authenticated() or ((int(pk_user) != request.user.pk)\
            and not request.user.is_superuser):
        raise Http404

    persons = Person.objects.filter(userCreator_id=pk_user)
    return render(request, 'persons/person_list.html', {'persons': persons})

def person_list(request):
    if not request.user.is_authenticated or not request.user.is_superuser:
        raise Http404

    persons = Person.objects.all()
    return render(request, 'persons/person_list.html', {'persons': persons})

def person_create(request):

    if not request.user.is_authenticated:
        raise Http404

    context = {}
    if request.method == 'POST':
        form = PersonForm(request.POST or None)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.userCreator = request.user
            instance.save()
            if request.user.is_superuser:
                return redirect('/persons/successful')
            return redirect(('/persons/personsuser/{0}'.format(request.user.pk)))
    else:
        form = PersonForm()

    context['form'] = form
    context['title'] = 'Insertar'

    return render(request, "persons/create.html", context)

def person_update(request, pk):
    if not request.user.is_authenticated():
        raise Http404

    instance = get_object_or_404(Person, pk=pk)
    if instance.userCreator != request.user and not request.user.is_superuser:
        raise Http404

    form = PersonForm(request.POST or None, instance=instance)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        if request.user.is_superuser:
            return redirect('/persons/successfuledition')
        return redirect(('/persons/personsuser/{0}'.format(request.user.pk)))

    context = {
        "person": instance,
        "form": form,
        'title': 'Editar'
    }

    return render(request, 'persons/create.html', context)

def person_delete(request, pk=None):
    if not request.user.is_authenticated():
        raise Http404

    instance = get_object_or_404(Person, pk=pk)

    if instance.userCreator != request.user and not request.user.is_superuser:
        raise Http404

    instance.delete()
    if request.user.is_superuser:
        return redirect('/persons/successfuldeletion/')
    return redirect(('/persons/personsuser/{0}'.format(request.user.pk)))

def users_list(request):
    if not request.user.is_authenticated() or not request.user.is_superuser:
        raise Http404

    users = User.objects.all()
    return render(request, 'persons/users_list.html', {'users': users})

def disable_user(request, pk):
    if not request.user.is_authenticated() or not request.user.is_superuser:
        raise Http404

    user = User.objects.get(pk=pk)
    user.is_active = False
    user.save()
    return redirect('/persons/users')

def enable_user(request, pk):
    if not request.user.is_authenticated or not request.user.is_superuser:
        raise Http404

    user = User.objects.get(pk=pk)
    user.is_active = True
    user.save()
    return redirect('/persons/users')

def search(request):
    if not request.user.is_authenticated():
        raise Http404
    if not request.user.is_superuser:
        return redirect('/persons/personsuser/{0}'.format(request.user.pk))
    return render(request, 'persons/search.html')

def results(request):
    if not request.user.is_authenticated() or not request.user.is_superuser:
        raise Http404

    name = request.GET['name']
    email = request.GET['email']
    phone = request.GET['phone']

    persons = Person.objects.filter(name__icontains=name, email__icontains=email, phone__icontains=phone)
    return render(request, 'persons/person_list.html', {'persons': persons})

def successful(request):
    if not request.user.is_authenticated():
        raise Http404
    return render(request, 'persons/successful.html', {'message': 'created'})

def successful_edition(request):
    if not request.user.is_authenticated:
        raise Http404
    return render(request, 'persons/successful.html', {'message': 'edited'})

def successful_deletion(request):
    if not request.user.is_authenticated:
        raise Http404
    return render(request, 'persons/successful.html', {'message': 'deleted'})

def successful_user(request):
    if not request.user.is_authenticated() or not request.user.is_superuser:
        raise Http404
    return render(request, 'persons/successful.html', {'message': 'user'})

class UserLoginView(View):

    def post(self, request):
        form_class = UserForm(data={'username': self.request.POST['username'],
                                    'password': self.request.POST['password']})

        username = self.request.POST['username']
        password = self.request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'persons/login.html', {'message': 'inactive'})
        return render(request, 'persons/login.html', {'message': 'invalid'})


class UserCreateView(View):

    form_class = CreateUserForm
    template_name = 'persons/create_user.html'

    def get(self, request):
        if not request.user.is_authenticated() or not request.user.is_superuser:
            raise Http404
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        if not request.user.is_authenticated() or not request.user.is_superuser:
            raise Http404
        form = self.form_class(request.POST)

        if form.is_valid():
            instance = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            instance.set_password(password)
            instance.save()

            return redirect('/persons/users')

        return render(request, self.template_name, {'form': form, 'message': 'error'})

persons/templates/persons/create.html
{% extends "layout.html" %}

{% block title %}Create Person{% endblock %}

{% block content %}
    <div class="create">
        <div class="page-header">
            <h1>{{ title }}</h1>
        </div>
        <form method="post" action=""> {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label_tag }}</label>
                    {% if field.errors %}
                        <div class="alert alert-danger">{{ field.errors }}</div>
                    {% endif %}
                    {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="Insertar">
        </form>
    </div>
{% endblock %}

persons/templates/persons/create_user.html
{% extends "layout.html" %}

{% block title %}Create User{% endblock %}

{% block content %}
    <div class="create">
        <div class="page-header">
            <h1>Crear Usuario</h1>
        </div>
        <form method="post" action=""> {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label>{{ field.label_tag }}</label>
                    {% if field.errors %}
                        <div class="alert alert-danger">{{ field.errors }}</div>
                    {% endif %}
                    {{ field }}
                </div>
            {% endfor %}
            <input type="submit" value="Crear Usuario">
        </form>
    </div>
{% endblock %}

persons/templates/persons/login.html
{% extends "layout.html" %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div id="login">
        <div class="page-header">
            <h1>Iniciar Sesión</h1>
        </div>
        {% if message == 'invalid'%}
            <div class="alert alert-danger">
                <strong>Usuario o contraseña inválidas</strong>
            </div>
        {% elif message == 'inactive'%}
            <div class="alert alert-danger">
                <strong>Este usuario ya está inactivo</strong>
            </div>
        {% endif %}

        <form method="post" action="{% url 'persons:login' %}" role="form">
            {% csrf_token %}
            <div class="form-group">
                <label>Username:</label>
                <input type="text" class="form-control" name="username">
            </div>
            <div class="form-group">
                <label for="pwd">Contraseña:</label>
                <input type="password" class="form-control" name="password">
            </div>
            <button type="submit" class="btn btn-default">Log In</button>
        </form>
    </div>
{% endblock %}

persons/templates/persons/person_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Create Person{% endblock %}

{% block content %}
    <div id="persons">
        <div class="page-header">
            <h1>Lista de personas</h1>
        </div>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nombre</th><th>Email</th><th>Teléfono</th>
                            <th>Edad</th><th>Género</th><th>Editar</th><th>Borrar</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for person in persons %}
                            <tr>
                                <td>{{ person.name }}</td>
                                <td>{{ person.email }}</td>
                                <td>{{ person.phone }}</td>
                                <td>{{ person.age }}</td>
                                <td>{{ person.gender }}</td>
                                <td><a href="{% url 'persons:update' pk=person.pk %}">
                                    <span class="label label-primary">Editar</span>
                                </a></td>
                                <td><a class="sure" href="{% url 'persons:delete' pk=person.pk %}">
                                    <span class="label label-danger">Borrar</span>
                                </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

persons/templates/persons/search.html
{% extends "layout.html" %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div id="search">
        <div class="page-header">
            <h1>Busqueda</h1>
        </div>
        <form method="get" action="{% url 'persons:results' %}" role="form">
            <div class="form-group">
                <label>Nombre</label>
                <input type="text" name="name" class="form-control">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" name="email" class="form-control">
            </div>
            <div class="form-group">
                <label>Teléfono</label>
                <input type="number" name="phone" class="form-control">
            </div>
            <button class="btn btn-default">Buscar</button>
        </form>
    </div>

{% endblock %}

persons/templates/persons/successful.html
{% extends "layout.html" %}

{% block title %}Log In{% endblock %}

{% block content %}
    <div class="create">
        {% if message == 'created' %}
            <h1>La información ha sido insertada exitosamente!</h1>
        {% elif message == 'deleted'%}
            <h1>La información ha sido eliminada!</h1>
        {% endif %}
        <a href="{% url 'persons:create' %}">
            <span class="label label-primary">Regresar</span>
        </a>
        {% if user.is_superuser %}
            <a href="{% url 'persons:all' %}">
                <span class="label label-primary">Ver lista completa</span>
            </a>
            <a href="{% url 'persons:search' %}">
                <span class="label label-primary">Buscar</span>
            </a>
        {% else %}
            <a href="{% url 'persons:personsuser' pk_user=user.pk %}">
                <span class="label label-primary">Ver lista</span>
            </a>
        {% endif %}
    </div>
{% endblock %}

persons/templates/persons/users_list.html
{% extends "layout.html" %}

{% block title %}Create Person{% endblock %}

{% block content %}

    <div id="users">
        <div class="page-header">
            <h1>Lista de Usuarios</h1>
        </div>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Usuario</th><th>Status</th><th>Activación</th>
                            <th>Información insertada</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user }}</td>
                                {% if user.is_active %}
                                    <td>Activo</td>
                                    <td><a href="{% url 'persons:disable' pk=user.pk %}">
                                        <span class="label label-danger">Desactivar</span>
                                    </a></td>
                                {% else %}
                                    <td>Inactivo</td>
                                    <td><a href="{% url 'persons:enable' pk=user.pk %}">
                                        <span class="label label-success">Activar</span>
                                    </a></td>
                                {% endif %}
                                <td>
                                    <a href="{% url 'persons:personsuser' pk_user=user.pk %}">
                                        <span class="label label-primary">Personas</span>
                                    </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}