SantaFeBD/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_view
from . import views

urlpatterns = [
    url(r'^persons/', include('persons.urls', namespace='persons')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
]

persons/urls.py
from django.conf.urls import url

from .views import (UserLoginView,
                    loginForm,
                    logoutView,
                    person_create,
                    person_update,
                    person_delete,
                    UserCreateView,
                    persons_list_creator,
                    users_list,
                    disable_user,
                    enable_user,
                    search,
                    results,
                    person_list,
                    successful,
                    successful_user,
                    successful_edition,
                    successful_deletion,
)

urlpatterns = [
    url('^login/$', UserLoginView.as_view(), name='login'),
    url('^logout/$', logoutView, name='logout'),
    url('^tologin/$', loginForm, name='tologin'),
    url('^create/$', person_create, name='create'),
    url('^edit/(?P<pk>\d+)/$', person_update, name='update'),
    url('^delete/(?P<pk>\d+)/$', person_delete, name='delete'),
    url('^createuser/$', UserCreateView.as_view(), name='createuser'),
    url('^users/$', users_list, name='users'),
    url('^personsuser/(?P<pk_user>\d+)/$', persons_list_creator, name='personsuser'),
    url('^disable/(?P<pk>\d+)/$', disable_user, name='disable'),
    url('^enable/(?P<pk>\d+)/$', enable_user, name='enable'),
    url('^search/$', search, name='search'),
    url('^results/$', results, name='results'),
    url('^successful/$', successful, name='successful'),
    url('^successfuluser/$', successful_user, name='succesfuluser'),
    url('^successfuledition/$', successful_edition, name='successfuledition'),
    url('^successfuldeletion/$', successful_deletion, name='successfuldeletion'),
    url('^$', person_list, name='all'),
]

templates/home.html
{% extends "layout.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="jumbotron">
        {% if user.is_authenticated %}
            <h1>Bienvenido {{ user }}</h1>
        {% else %}
            <h1>
                Este sitio es privado, si usted no es del personal autorizado para usar este sitio,
                le pedimos que se retire
            </h1>
        {% endif %}
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
<!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r"
          crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div id="high-screen">
                    <a class="navbar-brand" href="/">Home</a>
                    {% if user.is_authenticated %}
                        <a class="navbar-brand" href="{% url 'persons:logout' %}">Log out</a>
                        <a class="navbar-brand" href="{% url 'persons:search' %}">Buscar Personas</a>
                        <a class="navbar-brand" href="{% url 'persons:create' %}">Insertar Persona</a>
                    {% else %}
                        <a class="navbar-brand" href="{% url 'persons:tologin' %}">Log in</a>
                    {% endif %}

                    {% if user.is_superuser %}
                        <a class="navbar-brand" href="{% url 'persons:createuser' %}">Crear Cuenta</a>
                        <a class="navbar-brand" href="{% url 'persons:users' %}">Ver usuarios</a>
                    {% endif %}
                </div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar"
                            aria-expanded="true" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                            <li><a class="navbar-brand" href="/">Home</a></li>
                        <li><a class="navbar-brand" href="{% url 'persons:logout' %}">Log out</a></li>
                        <li><a class="navbar-brand" href="{% url 'persons:search' %}">Buscar Personas</a></li>
                        <li><a class="navbar-brand" href="{% url 'persons:create' %}">Insertar Persona</a></li>
                    {% else %}
                        <li><a class="navbar-brand" href="{% url 'persons:tologin' %}">Log in</a></li>
                    {% endif %}

                    {% if user.is_superuser %}
                        <li><a class="navbar-brand" href="{% url 'persons:createuser' %}">Crear Cuenta</a></li>
                        <li><a class="navbar-brand" href="{% url 'persons:users' %}">Ver usuarios</a></li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            {% block content %}{% endblock %}
        </div>

    </section>
    <footer>

    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>